### ISSUE TITLE
It is not clear how this library will substitute wow js

### ISSUE THREAD

**Issue by yerlanyr** [marlospomin/sight#2]
Of course the idea is brilliant. But how to do data-wow-delay functionality and other moments about api aren't that clear.

**Comment by marlospomin** [comment]
That hasn't been implemented just yet, I'm working on finding a better solution for the actual code that's in the repo, also, I'll be upgrading it to typescript, meanwhile if you have any other alternative feel free to use that instead. I'll keep this issue open and add that to the todo list, thanks!
